Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using NLog.Targets;
using StomatologyApp.Models;
using StomatologyApp.ViewModels.Customer;

namespace StomatologyApp.Controllers
{
    [Authorize]
    public class CustomerController : Controller
    {
        private readonly ICustomerRepository _customerRepository;
        private readonly IHostingEnvironment hostingEnvironment;

        public CustomerController(ICustomerRepository customerRepository, IHostingEnvironment hostingEnvironment)
        {
            _customerRepository = customerRepository;
            this.hostingEnvironment = hostingEnvironment;
        }

        public ViewResult GetCustomers()
        {
            var customers = _customerRepository.GetCustomers();

            return View(customers);
        }

        [HttpGet] 
        public IActionResult GetCustomer(int Id)
        {
            var customer = _customerRepository.GetCustomer(Id);

            if(customer == null)
            {
                ViewBag.ErrorMessage = "The customer does not exist";
                return View("NotFound");
            }

            return View(customer);
        }

        [HttpPost]
        public IActionResult SearchForCustomer (string searchName)
        {
            var customers = _customerRepository.SearchForCustomer(searchName);

            if (customers == null)
            {
                ViewBag.ErrorMessage = "The customer you were looking for does not exist";
                return View("NotFound");
            }

            return View("FoundCustomers", customers);            
        }


        [HttpGet]
        public ViewResult EditCustomer (int? Id)
        {
            var customer = _customerRepository.GetCustomer(Id.Value);

            if (customer == null)
            {
                ViewBag.ErrorMessage = "The user does not exist any longer";
                return View("NotFound");
            }

            CustomerEditVM _customer = new CustomerEditVM()
            {
                CustomerId = customer.CustomerId,
                Name = customer.Name,
                Address = customer.Address,
                TelephoneNumber = customer.TelephoneNumber
            };

            return View(_customer);
        }

        [HttpPost]
        public IActionResult EditCustomer (CustomerEditVM model)
        {
            if (ModelState.IsValid)
            {

                var customer = _customerRepository.GetCustomer(model.CustomerId);

                if (customer == null)
                {
                    ViewBag.ErrorMessage = "The customer does not exist.";
                    return View("NotFound");
                }

                customer.Name = model.Name;
                customer.TelephoneNumber = model.TelephoneNumber;
                customer.Address = model.Address;

                _customerRepository.UpdateCustomer(customer);
                return RedirectToAction("GetCustomers");

            }

            return View(model);
           
        }

        [HttpGet]
        public ViewResult CreateCustomer()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateCustomer (CustomerCreateVM customer)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;

                if(customer.Photo != null)
                {
                    string folder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + customer.Photo.FileName;
                    string pathFile = Path.Combine(folder, uniqueFileName);

                    customer.Photo.CopyTo(new FileStream(pathFile, FileMode.Create));
                }

                Customer _customer = new Customer
                {
                    Name = customer.Name,
                    Address = customer.Address,
                    TelephoneNumber = customer.TelephoneNumber,
                    PhotoPath = uniqueFileName
                };

                _customerRepository.AddCustomer(_customer);
                return RedirectToAction("GetCustomers");
            }

            return View(customer); 
        }


        [HttpPost]
        public  IActionResult DeleteCustomer(int Id)
        {
            var _customer = _customerRepository.GetCustomer(Id);

            if(_customer == null) 
            {
                ViewBag.ErrorMessage = "The customer does not exist.";
                return View("NotFound");
            }

            var customer = _customerRepository.DeleteCustomer(Id);
            return RedirectToAction("GetCustomers");

            
        }

    }
}

Controllers/DentalProcedureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StomatologyApp.Interfaces;
using StomatologyApp.Models;
using StomatologyApp.ViewModels.DentalProcedure;

namespace StomatologyApp.Controllers
{
    [Authorize]
    public class DentalProcedureController : Controller
    {
        private readonly IDentalProcedureRepository _dentalProcedure;

        public DentalProcedureController(IDentalProcedureRepository dentalProcedure)
        {
            _dentalProcedure = dentalProcedure;
        }

        [HttpGet]
        [AllowAnonymous]
        public ViewResult GetProcedures()
        {
            var procedures = _dentalProcedure.GetProcedures();

            return View(procedures);
        }

        [HttpGet]
        [AllowAnonymous]
        public ViewResult GetProcedure (int Id)
        {
            var procedure = _dentalProcedure.GetProcedure(Id);
            return View(procedure);
        }

        [HttpGet]
        public ViewResult EditProcedure (int? Id)
        {
            var procedure = _dentalProcedure.GetProcedure(Id.Value);

            if(procedure == null)
            {
                ViewBag.ErrorMessage = "The dental procedure does not exist";
                return View("NotFound");
            }

            DentalProcedureEditVM _procedure = new DentalProcedureEditVM
            {
                DentalProcedureId = procedure.DentalProcedureId,
                ProcedureName = procedure.ProcedureName,
                ProcedurePrice = procedure.ProcedurePrice
            };

            return View(_procedure);
        }

        [HttpPost]
        public IActionResult EditProcedure(DentalProcedureEditVM model)
        {
            if (ModelState.IsValid)
            {
                var procedure = _dentalProcedure.GetProcedure(model.DentalProcedureId);

                if (procedure == null)
                {
                    //ViewBag.ErrorMessage = "The procedure does not exist";
                    return View("NotFound");

                }

                procedure.ProcedureName = model.ProcedureName;
                procedure.ProcedurePrice = model.ProcedurePrice;

                _dentalProcedure.UpdateProcedure(procedure);

                return RedirectToAction("GetProcedures");

            }

            return View(model);
        }

        [HttpGet]
        public ViewResult CreateProcedure()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateProcedure(DentalProcedureCreateVM model)
        {


            if (ModelState.IsValid)
            {
                DentalProcedure procedure = new DentalProcedure
                {
                    ProcedureName = model.ProcedureName,
                    ProcedurePrice = model.ProcedurePrice
                };

                _dentalProcedure.AddProcedure(procedure);
                return RedirectToAction("GetProcedures");

            }

            return View(model);
        }

        [HttpPost]
        public IActionResult DeleteProcedure (int Id)
        {
            var procedure = _dentalProcedure.GetProcedure(Id);

            if(procedure == null)
            {
                ViewBag.ErrorMessage = "The procedure does not exist";
                return View("NotFound");

            }

            _dentalProcedure.DeleteProcedure(Id);
            return RedirectToAction("GetProcedures");

        }

    }
}

Controllers/WorkDayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StomatologyApp.Interfaces;
using StomatologyApp.Models;
using StomatologyApp.ViewModels;
using StomatologyApp.ViewModels.WorkDays;

namespace StomatologyApp.Controllers
{
    [Authorize]
    public class WorkDayController : Controller
    {
        private readonly IWorkDayRepository _workDay;

        public WorkDayController (IWorkDayRepository workDay)
        {
            _workDay = workDay;
        }

        [HttpGet]
        [AllowAnonymous]
        public ViewResult GetAllWorkWeeks()
        {
            var workWeek = _workDay.GetAllWorkWeeks();

            return View(workWeek);
        }

        [HttpGet]
        [AllowAnonymous]
        public ViewResult GetWorkWeek(int Id)
        {
            var workWeek = _workDay.GetWorkWeek(Id);

            return View(workWeek);
        }

        [HttpGet]
        public ViewResult EditWorkWeek(int? Id)
        {
            var workWeek = _workDay.GetWorkWeek(Id.Value);

            if (workWeek == null)
            {
                ViewBag.ErrorMessage = "The work week is not created";
                return View("NotFound");
            }

            WorkWeekEditVM _workWeek = new WorkWeekEditVM
            {
                WorkDaysId = workWeek.WorkDaysId,
                WorkWeekStart = workWeek.WorkWeekStart,
                WorkWeekEnd = workWeek.WorkWeekEnd,
            };

            return View(_workWeek);
        }

        [HttpPost]
        public IActionResult EditWorkWeek(WorkWeekEditVM model)
        {
            if (ModelState.IsValid)
            {
                var workWeek = _workDay.GetWorkWeek(model.WorkDaysId);

                if (workWeek == null)
                {
                    return View("NotFound");

                }

                workWeek.WorkWeekStart = model.WorkWeekStart;
                workWeek.WorkWeekEnd = model.WorkWeekEnd;

                _workDay.UpdateWorkWeek(workWeek);

                return RedirectToAction("GetAllWorkWeeks");

            }

            return View(model);
        }

        [HttpGet]
        public ViewResult AddWorkWeek()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddWorkWeek(WorkWeekCreateVM model)
        {


            if (ModelState.IsValid)
            {
                WorkDays workWeek = new WorkDays
                {
                    WorkWeekStart = model.WorkWeekStart,
                    WorkWeekEnd = model.WorkWeekEnd,
                };

                _workDay.AddWorkWeek(workWeek);
                return RedirectToAction("GetAllWorkWeeks");

            }

            return View(model);
        }

        [HttpPost]
        public IActionResult DeleteWorkWeek(int Id)
        {
            var workWeek = _workDay.GetWorkWeek(Id);

            if (workWeek == null)
            {
                ViewBag.ErrorMessage = "The work week is not created";
                return View("NotFound");

            }

            _workDay.DeleteWorkWeek(Id);
            return RedirectToAction("GetAllWorkWeeks");

        }
    }
}

Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
}

@if (ViewBag.ErrorMessage == null)
{
    <h2>
        Unfortunately, we could not find what you were looking for
    </h2>

    <br />
    <h6><a asp-action="Index" asp-controller="Home">return home</a></h6>
}
else
{
    <h2>
        @ViewBag.ErrorMessage
    </h2>

    <br />
    <h6><a asp-action="GetCustomers" asp-controller="Customer">return home</a></h6>
}

Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> signInManager;
<html>
<head>

    <meta name="viewport" content="width=device-width" />

    <script src="~/lib/jquery/jquery.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/jquery.min.js"></script>*@
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    @*<script src="~/lib/bootstrap/js/bootstrap.min.js"></script>*@

    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    @*<link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />*@
    <link href="~/lib/bootstrap/js/css/bootstrap-datepicker.css" rel="stylesheet" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="~/css/site.css"/>
    <title>@ViewBag.Title</title>
</head>
<body>


    <div class="container">
        <a class="navbar-brand" asp-action="Index" asp-controller="Home">
            <img src="~/images/icons8-tooth-100.png" style="float:left" height="50" width="50"/>
        </a>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                {
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-item nav-link" asp-action="Index" asp-controller="Home">Appointments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link" asp-action="GetCustomers" asp-controller="Customer">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link" asp-action="GetProcedures" asp-controller="DentalProcedure">Dental procedures</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link" asp-action="GetAllWorkWeeks" asp-controller="WorkDay">Work schedules</a>
                        </li>
                    </ul>
                }
                else {
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-item nav-link" asp-action="GetProcedures" asp-controller="DentalProcedure">Dental procedures</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" asp-action="GetAllWorkWeeks" asp-controller="WorkDay">Work schedules</a>
                    </li>
                </ul>
                }

                <ul class="navbar-nav w-25">
                    @if (signInManager.IsSignedIn(User))
                    {
                        <li class="nav-item ml-auto">
                            <form method="post" asp-action="logout" asp-controller="Account">
                                <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                                    Logout @User.Identity.Name
                                </button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item ml-auto">
                            @*//udesno*@
                            @*<a class="nav-item nav-link" asp-action="Register" asp-controller="Account">Register</a>*@
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-item nav-link" asp-action="Login" asp-controller="Account">Login</a>
                        </li>
                    }


                </ul>
            </div>
        </nav>
        <div class="container">
            @RenderBody()
        </div>
        @if (IsSectionDefined("Scripts"))
        {
            @RenderSection("Scripts")
        }
    </div>

</body>
</html>